package com.zhaoProject.springBoot.domain;

public class PrizeBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_prize_base.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_prize_base.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_prize_base.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_prize_base.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_prize_base.prize_type
     *
     * @mbggenerated
     */
    private Byte prizeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_prize_base.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_prize_base.is_sys
     *
     * @mbggenerated
     */
    private Byte isSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_prize_base.select_sum
     *
     * @mbggenerated
     */
    private Integer selectSum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_prize_base.id
     *
     * @return the value of tb_prize_base.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_prize_base.id
     *
     * @param id the value for tb_prize_base.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_prize_base.title
     *
     * @return the value of tb_prize_base.title
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_prize_base.title
     *
     * @param title the value for tb_prize_base.title
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_prize_base.info
     *
     * @return the value of tb_prize_base.info
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_prize_base.info
     *
     * @param info the value for tb_prize_base.info
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_prize_base.image_url
     *
     * @return the value of tb_prize_base.image_url
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_prize_base.image_url
     *
     * @param imageUrl the value for tb_prize_base.image_url
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_prize_base.prize_type
     *
     * @return the value of tb_prize_base.prize_type
     * @mbggenerated
     */
    public Byte getPrizeType() {
        return prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_prize_base.prize_type
     *
     * @param prizeType the value for tb_prize_base.prize_type
     * @mbggenerated
     */
    public void setPrizeType(Byte prizeType) {
        this.prizeType = prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_prize_base.type
     *
     * @return the value of tb_prize_base.type
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_prize_base.type
     *
     * @param type the value for tb_prize_base.type
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_prize_base.is_sys
     *
     * @return the value of tb_prize_base.is_sys
     * @mbggenerated
     */
    public Byte getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_prize_base.is_sys
     *
     * @param isSys the value for tb_prize_base.is_sys
     * @mbggenerated
     */
    public void setIsSys(Byte isSys) {
        this.isSys = isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_prize_base.select_sum
     *
     * @return the value of tb_prize_base.select_sum
     * @mbggenerated
     */
    public Integer getSelectSum() {
        return selectSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_prize_base.select_sum
     *
     * @param selectSum the value for tb_prize_base.select_sum
     * @mbggenerated
     */
    public void setSelectSum(Integer selectSum) {
        this.selectSum = selectSum;
    }
}