package com.zhaoProject.springBoot.dao;


import com.zhaoProject.springBoot.domain.PrizeBase;
import org.apache.ibatis.annotations.Select;

public interface PrizeBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_base
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_base
     *
     * @mbggenerated
     */
    int insert(PrizeBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_base
     *
     * @mbggenerated
     */
    int insertSelective(PrizeBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_base
     *
     * @mbggenerated
     */
    PrizeBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_base
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrizeBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_base
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrizeBase record);

    @Select("select * from tb_prize_base where id = #{id}")
    public PrizeBase getById(int id);
}